# -*- coding: utf-8 -*-
"""Chapter1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N9TzNqEZImo3erxGFfrcc8w3-41BZvrH
"""

#TYPE CONVERSION

#implicit Type Coversion

num_integer=123
num_float=1.23

sum= num_integer + num_float
print(sum)

#print type of variable using type() function
print("Type of a:",type(sum))

#explicit Type Conversion

float_num=1.734
integer_num=int(float_num)
print(integer_num)
print(type(integer_num))

#String to int and float
a='53'
integer_num=int(a)
float_num=float(a)

print('integer_num:',integer_num)
print('float_num:',float_num)

#int and float to string

a=80
b=80.99

str_a=str(a)
str_b=str(b)

print(str_a)
print(type(str_a))

print(str_b)
print(type(str_b))

#error during Type Conversion

a='hello'
integer_num=int(a)

#Loss of information during conversion

float_num=5.67
integer_number=int(float_num)

print("float_num:",float_num)
print("integer_num:",integer_number)

#ASSIGNMENT OPERATOR

# '+='

x=10
x+=5

print(x)

# '//='

x=10
x//=4

print(x)

#OPERATOR PRECEDENCE

print(10-4*2)

#The output of the above example will be 2, not 12.
#It's because the order operator precedence of * is higher than -. Meaning, *operation is carried out before -.
#This is known as OPERATOR PRECEDENCE. It guides the order in which th operation is carried out.

#The operator precedence in python is listed below from higher order  to lower order.
# () > ** > +x,-x > *,/,//,% > +,-

str1='abc'
print(str1*3)

print((10-4)*2-1)

